import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "~/query/client";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" className="dark">
      <body
        className={`${geistMono.variable} font-mono antialiased overscroll-none min-h-screen relative`}
      >
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <div
          style={{
            backgroundImage: "url(/media/bg-noise.png)",
          }}
          className="pointer-events-none [z-index:-1] absolute inset-0 bg-[size:180px] bg-repeat opacity-[0.035] dark:opacity-[0.015]"
        ></div>
      </body>
    </html>
  );
}
